### ISSUE TITLE
Trouble with precompile assets

### ISSUE THREAD

**Issue by lxkuz** [requirejs/requirejs#1122]
In production mode we need precompiled assets to one js file. But when I use external libs without AMD interface by wrap them via path and shim options in config file:

``` yaml
paths:
  jquery_ujs: 'bower_components/jquery-ujs/src/rails'
shim:
  jquery_ujs:
    deps: [
      'jquery'
    ]

  app:
    deps: [
      'jquery_ujs'
```

I got in result file:

``` javascript
// code of ALL jquery_ujs lib HERE!!!!
define("jquery_ujs", ["jquery"], function(){});
```

So this lib do not using amd-mechanism. What I doing wrong?
