### ISSUE TITLE
2.1.8: loading from "sub/theFile" fails (no error) but moving the file and loading from "sub/anotherDir/theFile" succeeds

### ISSUE THREAD

**Issue by jcollum-hcg** [requirejs/requirejs#894]
This one has been perplexing me today. I've got a working app that I've been building for a few months. I got the require.js stuff sorted out a while back. But suddenly, today, it simply isn't working. But only in one specific spot. Here's the setup (coffeescript):

```
require.config
  paths:
    angular: "//cdn.jsdelivr.net/angularjs/1.1.2/angular"
    text: "lib/require/text"
    'jqueryui' : '//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min',
    'jquery': '//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min'
    'moment': '//cdnjs.cloudflare.com/ajax/libs/moment.js/1.7.2/moment.min'
    'cdn-lodash' : '//cdnjs.cloudflare.com/ajax/libs/lodash.js/1.3.1/lodash'
    'angular-router' : 'lib/angular/angular-ui-router'
    'angular-resource' : '//cdn.jsdelivr.net/angularjs/1.1.2/angular-resource.min'
    'angular-dragdrop' : 'lib/angular/angular-dragdrop'
    'angular-ui' : 'lib/angular/ui-bootstrap-tpls-0.4.0'
    'local': './local'
    'jslib': './lib'

  baseUrl: "js"
  shim:
    angular:
      exports: "angular"
    jqueryui:
      deps: ['jquery']
    angularMocks:
      deps: ["angular"]
      exports: "angular.mock"

  priority: ["angular"]
  waitSeconds: 20
```

OK so the "local" path is the important part, that's where all my code sits. Here's a sample require: 

```
require(["local/calc/kappa", 'cdn-lodash' ],
  (Kappa, lodash)->

```

The Kappa library is loading fine. 

But this require: 

```
require(['local/alpha', "local/gamma", "local/delta"], (Alpha, Gamma, Delta) ->
```

Results in failure. Not an error, just no code being loaded (Alpha is undef). However, if I _move_ those files into a subfolder: 

```
require(['local/u/alpha', "local/u/gamma", "local/u/delta"], (Alpha, Gamma, Delta) ->
```

Just to be clear, the files were not present in local/u before I put them there. The objects load fine. In the first case there is a request being sent to the server for only the first one (GET to /js/local/alpha.js) -- but not the next two. All the files are present on the server (I can load them via url directly in the browser). 

If this isn't a bug it's definitely an example of not erroring when it should. Can I turn up the error throwing somehow? Right now it's just silently failing on a valid url. There's nothing in the error logs. 

What would really help is if you could tell me what line of code require uses to actually do the GET to the server. I've been looking through the code and I can't find it. Maybe if I put a BP there I can see what url it's trying to use. 

Here's a sample of the JS file that I'm loading: 

```
(function() {

  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function() {
    var Delta;
    return Delta = (function() {
      function Delta(_arg) {
        var _base;
        this.logger = _arg.logger, this.config = _arg.config,  this.util = _arg.util;
        this.leave = __bind(this.leave, this);
        // ETC...
      }

      return Delta;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=Delta.js.map
*/
```
